apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: "-05"
namespace: hitter

bases:
  - ../../base


configMapGenerator:
  - name: hey-config
    behavior: create
    options:
      disableNameSuffixHash: true
    literals:
      - HEY_N=1000000
      - HEY_C=5
      - HEY_M=GET
      - HEY_TARGET=http://phpdemo.phpdemo