apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -hitter-01

bases:
  - ../../base


configMapGenerator:
  - name: hey-config
    namespace: hitter
    behavior: create
    literals:
      - HEY_N=1000000
      - HEY_C=100
      - HEY_M=GET
      - HEY_TARGET=http://phpdemo.phpdemo