apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: "-mckensson"
namespace: hitter

bases:
  - ../../cronjob

configMapGenerator:
  - name: hey-config
    behavior: create
    options:
      disableNameSuffixHash: true
    literals:
      - HEY_N=10
      - HEY_C=1
      - HEY_M=GET
      - HEY_TARGET=http://10.220.48.68:6443