---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitme
  namespace: hitter
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: hitme
  template:
    metadata:
      name: hey-pod
    spec:
      containers:
        - name: hitter
          image: hitme
          command: ["/app/hey", "-n", $(HEY_N), "-c", $(HEY_C), "-m", "$(HEY_M)", "$(HEY_TARGET)"]
          resources:
            requests:
              cpu: "100m"
              memory: 100Mi
            limits:
              cpu: "400m"
              memory: 200Mi
      restartPolicy: Always
      imagePullSecrets:
        - name:  regcred-pv