apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: hitter
  name: hitme
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: memory
      target:
       averageValue: 100Mi
       type: AverageValue
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    namespace: hitter
    name: hitme