apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hitter

commonLabels:
  app: hitme 

resources:
  # - hpa.yaml
  - hitme-deploy.yaml
  # - cronjob.yaml
  # - ns.yaml

configurations:
  - "nameReferences.yaml"

images:
- name: hitme
  newName: pupimvictor/hitme
  newTag: latest

patches:
  - target:
      kind: Deployment
      # labelSelector: app=hitme
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: HEY_N
            valueFrom:
              configMapKeyRef:
                name: hey-config
                key: HEY_N
          - name: HEY_C
            valueFrom:
              configMapKeyRef:
                name: hey-config
                key: HEY_C
          - name: HEY_M
            valueFrom:
              configMapKeyRef:
                name: hey-config
                key: HEY_M
          - name: HEY_TARGET
            valueFrom:
              configMapKeyRef:
                name: hey-config
                key: HEY_TARGET
  